name: DePIN Mining Factory

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Tools
      run: |
        pip install httpx asyncio setuptools

    - name: Run Multi Node Mining
      env:
        GRASS_USER: ${{ secrets.GRASS_USER }}
        GRASS_PASS: ${{ secrets.GRASS_PASS }}
      run: |
        python COOLDUDE/main1.py
